version: "3.9"

services:
  backend:
    build: .
    container_name: chat-backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app        # live code sync
      - /app/__pycache__      # avoid overwriting cache
    env_file:
      - .env                  # optional
    command: uvicorn app.main:app --host 0.0.0.0 --reload
  db:
    image: postgres:15
    container_name: chat-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 55555
      POSTGRES_DB: test_db
    ports:
      - "5433:5432" # host port: container port
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: