"""create users table

Revision ID: 245d0bcbb8bf
Revises: d4e7d1fb26fe
Create Date: 2025-09-11 16:34:12.800475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245d0bcbb8bf'
down_revision: Union[str, Sequence[str], None] = 'd4e7d1fb26fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=False,server_default="temp_password"))
    # ### end Alembic commands ###
    op.alter_column("users", "password", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
