"""create messages table and add fields to user table

Revision ID: e97b076bc575
Revises: 245d0bcbb8bf
Create Date: 2025-09-30 13:07:54.742790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97b076bc575'
down_revision: Union[str, Sequence[str], None] = '245d0bcbb8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('file', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('file_type', sa.Enum('IMAGE', 'VIDEO', name='filetype'), nullable=True))
    op.drop_column('messages', 'image_video')
    op.add_column('users', sa.Column('connection_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('socket_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'socket_id')
    op.drop_column('users', 'connection_status')
    op.add_column('messages', sa.Column('image_video', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'file_type')
    op.drop_column('messages', 'file')
    # ### end Alembic commands ###
